// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MiniApp.Data;

#nullable disable

namespace MiniApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422175143_AddDrawPurchaseClosesAtUtc")]
    partial class AddDrawPurchaseClosesAtUtc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
#pragma warning restore 612, 618
        }
    }
}

