namespace MiniApp.Features.Localization;

internal static class LocalizationDefaults
{
    public static readonly IReadOnlyDictionary<string, (string En, string Ru, string Uz)> Entries
        = new Dictionary<string, (string En, string Ru, string Uz)>(StringComparer.Ordinal)
        {
            ["client.tab.home"] = ("Home", "Главная", "Bosh sahifa"),
            ["client.tab.tickets"] = ("My Tickets", "Мои билеты", "Mening biletlarim"),
            ["client.tab.profile"] = ("Profile", "Профиль", "Profil"),
            ["client.balance.label"] = ("Money", "Баланс", "Balans"),
            ["client.brand.title"] = ("LottoVibe", "ЛоттоВайб", "LottoVibe"),
            ["client.jackpot.alert"] = ("Jackpot alert", "Джекпот", "Jekpot"),
            ["client.jackpot.endsIn"] = ("Ends in --:--:--", "До конца --:--:--", "Tugashiga --:--:--"),
            ["client.jackpot.subtitle"] = ("The next draw is coming soon. Get your tickets now.", "Следующий тираж скоро начнется. Успейте купить билеты.", "Keyingi tiraj tez orada boshlanadi. Biletlarni hoziroq oling."),
            ["client.currentDraw.subtitle"] = ("Next draw and ticket purchase", "Следующий тираж и покупка билетов", "Keyingi tiraj va bilet xaridi"),
            ["client.currentDraw.waiting"] = ("waiting", "ожидание", "kutilmoqda"),
            ["client.currentDraw.empty"] = ("There is no active draw right now.", "Сейчас нет активного тиража.", "Hozir faol tiraj yoq."),
            ["client.currentDraw.ticketCostPrefix"] = ("Ticket cost:", "Цена билета:", "Bilet narxi:"),
            ["client.currentDraw.ticketCostSuffix"] = ("per entry.", "за один билет.", "har bir bilet uchun."),
            ["client.currentDraw.winningNumbers"] = ("Winning numbers", "Выигрышные числа", "Yutuq raqamlari"),
            ["client.currentDraw.noActiveTitle"] = ("No active draw available.", "Нет активного тиража.", "Faol tiraj mavjud emas."),
            ["client.currentDraw.concludedPrefix"] = ("Concluded ", "Завершен ", "Yakunlangan "),
            ["client.currentDraw.openedPrefix"] = ("Opened ", "Открыт ", "Ochilgan "),
            ["client.currentDraw.liveSubtitle"] = ("The draw is live. Don't miss your chance to become a multi-millionaire!", "Тираж уже идет. Не упустите шанс стать мультимиллионером!", "Tiraj jonli. Multimillioner bolish imkoniyatini boy bermang!"),
            ["client.currentDraw.finishedWithWinnings"] = ("This draw is finished and your winnings are ready to claim.", "Этот тираж завершен, и ваш выигрыш готов к получению.", "Bu tiraj yakunlangan va yutugingizni olishingiz mumkin."),
            ["client.currentDraw.finishedNoWinnings"] = ("This draw is finished. Check your tickets against the result numbers.", "Этот тираж завершен. Сверьте билеты с результатами.", "Bu tiraj yakunlangan. Biletlaringizni natijalar bilan tekshiring."),
            ["client.currentDraw.activeOnlyTitle"] = ("Only the active draw accepts purchases.", "Покупка доступна только для активного тиража.", "Faqat faol tiraj uchun xarid qilish mumkin."),
            ["client.tickets.title"] = ("My tickets", "Мои билеты", "Mening biletlarim"),
            ["client.tickets.empty"] = ("You have not bought any tickets yet.", "Вы еще не купили ни одного билета.", "Siz hali birorta bilet sotib olmadingiz."),
            ["client.profile.title"] = ("Profile", "Профиль", "Profil"),
            ["client.profile.subtitle"] = ("Manage your wallet balance.", "Управляйте балансом кошелька.", "Hamyon balansini boshqaring."),
            ["client.profile.currentBalance"] = ("Current balance:", "Текущий баланс:", "Joriy balans:"),
            ["client.profile.savedWallet"] = ("Saved wallet address", "Сохраненный адрес кошелька", "Saqlangan hamyon manzili"),
            ["client.profile.walletPlaceholder"] = ("Bitcoin wallet address", "Адрес Bitcoin-кошелька", "Bitcoin hamyon manzili"),
            ["client.profile.withdrawTitle"] = ("Request withdrawal", "Запрос на вывод", "Pul yechish so'rovi"),
            ["client.profile.amountPlaceholder"] = ("Amount", "Сумма", "Miqdor"),
            ["client.profile.withdrawAddressPlaceholder"] = ("Wallet address (or leave empty to use saved)", "Адрес кошелька (или оставьте пустым, чтобы использовать сохраненный)", "Hamyon manzili (yoki saqlanganni ishlatish uchun bo'sh qoldiring)"),
            ["client.button.purchase"] = ("Purchase ticket", "Купить билет", "Bilet sotib olish"),
            ["client.button.deposit"] = ("Deposit crypto", "Пополнить криптой", "Kripto toldirish"),
            ["client.button.withdraw"] = ("Withdraw", "Вывести", "Yechib olish"),
            ["client.button.saveWallet"] = ("Save wallet address", "Сохранить адрес", "Hamyon manzilini saqlash"),
            ["client.button.openHistory"] = ("Transaction history", "История транзакций", "Tranzaksiya tarixi"),
            ["client.button.back"] = ("Back", "Назад", "Orqaga"),
            ["client.history.title"] = ("Transaction history", "История транзакций", "Tranzaksiya tarixi"),
            ["client.history.empty"] = ("No transactions yet.", "Пока нет транзакций.", "Hali tranzaksiyalar yoq."),
            ["client.history.drawPrefix"] = ("Draw #", "Тираж #", "Tiraj #"),
            ["client.history.createdLegacy"] = ("Created before current format", "Создано до текущего формата", "Joriy formatdan oldin yaratilgan"),
            ["client.history.statePrefix"] = ("State:", "Статус:", "Holat:"),
            ["client.history.prizePoolPrefix"] = ("Prize pool:", "Призовой фонд:", "Mukofot jamgarmasi:"),
            ["client.history.noTicketsForDraw"] = ("No tickets for this draw.", "Для этого тиража нет билетов.", "Bu tiraj uchun biletlar yoq."),
            ["client.picker.title"] = ("Pick your numbers", "Выберите числа", "Raqamlaringizni tanlang"),
            ["client.picker.subtitle"] = ("Choose 5 unique numbers from 1 to 36.", "Выберите 5 уникальных чисел от 1 до 36.", "1 dan 36 gacha 5 ta noyob raqamni tanlang."),
            ["client.picker.closeAria"] = ("Close picker", "Закрыть выбор", "Tanlash oynasini yopish"),
            ["client.picker.gridAria"] = ("Number picker", "Выбор чисел", "Raqam tanlash"),
            ["client.popup.error"] = ("Error", "Ошибка", "Xatolik"),
            ["client.popup.confirm"] = ("Confirm", "Подтвердить", "Tasdiqlash"),
            ["client.ticket.status.winningsAvailable"] = ("Winnings available", "Выигрыш доступен", "Yutuq mavjud"),
            ["client.ticket.status.winningsClaimed"] = ("Winnings claimed", "Выигрыш получен", "Yutuq olindi"),
            ["client.ticket.status.expired"] = ("Expired", "Истек", "Muddati tugagan"),
            ["client.ticket.status.awaiting"] = ("Waiting for draw", "Ожидание тиража", "Tiraj kutilmoqda"),
            ["client.ticket.claimPrefix"] = ("Claim", "Получить", "Olish"),
            ["client.ticket.claimedPrefix"] = ("Claimed", "Получено", "Olindi"),
            ["client.ticket.claiming"] = ("Claiming winnings...", "Получение выигрыша...", "Yutuq olinmoqda..."),
            ["client.ticket.claimFailed"] = ("Claim failed.", "Не удалось получить выигрыш.", "Yutuqni olish muvaffaqiyatsiz."),
            ["client.status.loadingHistory"] = ("Loading transaction history...", "Загрузка истории транзакций...", "Tranzaksiya tarixi yuklanmoqda..."),
            ["client.status.noActiveDraw"] = ("There is no active draw right now.", "Сейчас нет активного тиража.", "Hozir faol tiraj yoq."),
            ["client.status.ticketPurchased"] = ("Ticket purchased.", "Билет куплен.", "Bilet sotib olindi."),
            ["client.status.purchaseFailed"] = ("Purchase failed.", "Покупка не удалась.", "Xarid muvaffaqiyatsiz."),
            ["client.status.authenticationFailed"] = ("Authentication failed.", "Ошибка авторизации.", "Autentifikatsiya muvaffaqiyatsiz."),
            ["client.picker.preparing"] = ("Preparing numbers...", "Подготовка чисел...", "Raqamlar tayyorlanmoqda..."),
            ["client.picker.chooseUnique"] = ("Please choose 5 unique numbers.", "Выберите 5 уникальных чисел.", "Iltimos, 5 ta noyob raqam tanlang."),
            ["client.picker.submitting"] = ("Submitting ticket...", "Отправка билета...", "Bilet yuborilmoqda..."),
            ["client.picker.confirm"] = ("Confirm numbers", "Подтвердить числа", "Raqamlarni tasdiqlash"),
            ["admin.nav.localization"] = ("Localization", "Локализация", "Lokalizatsiya"),
            ["admin.localization.title"] = ("Localization", "Локализация", "Lokalizatsiya"),
            ["admin.localization.subtitle"] = ("Update en / ru / uz UI strings.", "Обновляйте тексты интерфейса en / ru / uz.", "en / ru / uz UI matnlarini yangilang."),
            ["bot.welcomeBack"] = ("Welcome back!", "С возвращением!", "Xush kelibsiz!"),
            ["bot.openMiniApp"] = ("Open Mini App", "Открыть Mini App", "Mini Appni ochish"),
            ["bot.changeLanguage"] = ("Change language", "Сменить язык", "Tilni ozgartirish"),
            ["bot.tapOpenMiniApp"] = ("Tap the button below to open the Mini App.", "Нажмите кнопку ниже, чтобы открыть Mini App.", "Mini Appni ochish uchun pastdagi tugmani bosing."),
            ["bot.askLanguage"] = ("Please choose your language:", "Пожалуйста, выберите язык:", "Iltimos, tilni tanlang:"),
            ["bot.askContact"] = ("Please share your contact to continue.", "Пожалуйста, отправьте контакт, чтобы продолжить.", "Davom etish uchun kontakt yuboring."),
            ["bot.shareContact"] = ("Share my contact", "Поделиться контактом", "Kontaktni yuborish"),
            ["bot.savedNumber"] = ("Thanks! Saved.", "Спасибо! Сохранено.", "Rahmat! Saqlandi."),
            ["bot.invalidNumber"] = ("I could not read a valid phone number. Please tap 'Share my contact' or send the number as text.", "Не удалось распознать номер. Нажмите 'Поделиться контактом' или отправьте номер текстом.", "Raqamni oqib bolmadi. 'Kontaktni yuborish' tugmasini bosing yoki raqamni matn qilib yuboring."),
            ["bot.languageUpdated"] = ("Language updated.", "Язык обновлен.", "Til yangilandi."),
            ["bot.languageBeforePhone"] = ("First choose a language.", "Сначала выберите язык.", "Avval tilni tanlang."),
            ["bot.askPhonePlaceholder"] = ("Tap the button to share your phone number", "Нажмите кнопку, чтобы поделиться номером", "Telefon raqamingizni yuborish uchun tugmani bosing")
        };
}

